### ISSUE TITLE
Qodana linter fails on self-hosted action runner

### ISSUE THREAD

**Issue by daschneider** [JetBrains/qodana-action-eap#2]
Pull down action image 'jetbrains/qodana-jvm-community'
  /usr/bin/docker pull jetbrains/qodana-jvm-community
  Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=jetbrains%2Fqodana-jvm-community&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
  Using default tag: latest
  Warning: Docker pull failed with exit code 1, back off 8.104 seconds before retry.
  /usr/bin/docker pull jetbrains/qodana-jvm-community
  Using default tag: latest
  Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=jetbrains%2Fqodana-jvm-community&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
  Warning: Docker pull failed with exit code 1, back off 2.67 seconds before retry.
  /usr/bin/docker pull jetbrains/qodana-jvm-community
  Using default tag: latest
  Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=jetbrains%2Fqodana-jvm-community&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
Error: Docker pull failed with exit code 1

**Comment by tiulpin** [comment]
Hi! Sorry for the long reply, moved to https://youtrack.jetbrains.com/issue/QD-2079 (please watch the issue in case you still have problems or want to add some info)
We will try to reproduce it with our updated GitHub Action – https://github.com/jetbrains/qodana-action
